language: java

addons:
  sonarcloud:
    organization: "napstr-github"

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle/wrapper"
    - "$HOME/.gradle/caches"
    - "$HOME/.sonar/cache"

stages:
  - build & test
  - sonar

jobs:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
  include:
    - stage: build & test
      jdk: openjdk11
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: oraclejdk11
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: openjdk12
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: openjdk-ea
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"


    - stage: sonar
      jdk: openjdk11
      before_script:
        #for full sonar cloud blame information
        - "git fetch --unshallow"
      script:
        - "./gradlew sonarqube"
